In [102]:
import pandas as pd
import numpy as np

In [103]:
df = pd.read_csv("student_performance.csv")

In [104]:
df =df.drop(columns = ['math_score','science_score','english_score','final_grade','student_id','age'])

In [105]:
df.head()

,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,53.1
1,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,61.3
2,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,89.6
3,other,public,high school,1.1,58.1,no,15-30 min,no,notes,41.6
4,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,25.4

In [106]:
df = df.drop_duplicates()

In [107]:
df.isnull().sum()

gender                   0
school_type              0
parent_education         0
study_hours              0
attendance_percentage    0
internet_access          0
travel_time              0
extra_activities         0
study_method             0
overall_score            0
dtype: int64

In [108]:
df.duplicated().sum()

np.int64(0)

# train test split

In [109]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['overall_score']),df['overall_score'],
                                                test_size=0.2)

In [110]:
X_train

,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method
14515,other,public,no formal,0.9,70.8,yes,15-30 min,yes,online videos
6552,other,public,post graduate,0.6,73.7,yes,15-30 min,no,online videos
14971,other,public,no formal,1.6,59.3,yes,<15 min,yes,coaching
1548,other,public,phd,1.4,55.8,yes,15-30 min,no,notes
1880,other,private,phd,5.5,78.4,yes,<15 min,yes,textbook
...,...,...,...,...,...,...,...,...,...
1839,male,private,post graduate,2.0,84.1,yes,15-30 min,yes,mixed
4110,male,public,phd,1.9,72.6,yes,<15 min,yes,notes
10774,female,private,graduate,2.3,78.5,yes,<15 min,no,coaching
3852,female,private,graduate,1.6,62.8,yes,15-30 min,no,mixed
12782,female,private,post graduate,5.2,57.9,yes,30-60 min,no,group study

# Ordinal encoding

In [111]:
from sklearn.preprocessing import OrdinalEncoder
# Ordinalencoding -> parent_education,travel_time
oe = OrdinalEncoder(categories=[
    ['no formal','high school','diploma','graduate','post graduate','phd'],
    ['<15 min','15-30 min','30-60 min','>60 min']])
X_train[['parent_education','travel_time']] = oe.fit_transform(X_train[['parent_education','travel_time']])
# also the test data
X_test[['parent_education','travel_time']] = oe.fit_transform(X_test[['parent_education','travel_time']])

In [112]:
X_train['travel_time']

14515    1.0
6552     1.0
14971    0.0
1548     1.0
1880     0.0
        ...
1839     1.0
4110     0.0
10774    0.0
3852     1.0
12782    2.0
Name: travel_time, Length: 12000, dtype: float64

In [113]:
X_train['parent_education']

14515    0.0
6552     4.0
14971    0.0
1548     5.0
1880     5.0
        ...
1839     4.0
4110     5.0
10774    3.0
3852     3.0
12782    4.0
Name: parent_education, Length: 12000, dtype: float64

# column transformer